/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueDoctorIdRouteImport } from './routes/queue.$doctorId'
import { Route as PatientAuthRouteImport } from './routes/patient.auth'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as ConfirmationIdRouteImport } from './routes/confirmation.$id'
import { Route as BookDoctorIdRouteImport } from './routes/book.$doctorId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPatientDashboardRouteImport } from './routes/_authenticated/patient.dashboard'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor.profile'
import { Route as AuthenticatedDoctorPendingRouteImport } from './routes/_authenticated/doctor.pending'
import { Route as AuthenticatedDoctorOnboardingRouteImport } from './routes/_authenticated/doctor.onboarding'
import { Route as AuthenticatedDoctorDashboardRouteImport } from './routes/_authenticated/doctor.dashboard'

const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueDoctorIdRoute = QueueDoctorIdRouteImport.update({
  id: '/queue/$doctorId',
  path: '/queue/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAuthRoute = PatientAuthRouteImport.update({
  id: '/patient/auth',
  path: '/patient/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorsRoute,
} as any)
const ConfirmationIdRoute = ConfirmationIdRouteImport.update({
  id: '/confirmation/$id',
  path: '/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientDashboardRoute =
  AuthenticatedPatientDashboardRouteImport.update({
    id: '/patient/dashboard',
    path: '/patient/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/doctor/profile',
    path: '/doctor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorPendingRoute =
  AuthenticatedDoctorPendingRouteImport.update({
    id: '/doctor/pending',
    path: '/doctor/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorOnboardingRoute =
  AuthenticatedDoctorOnboardingRouteImport.update({
    id: '/doctor/onboarding',
    path: '/doctor/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorDashboardRoute =
  AuthenticatedDoctorDashboardRouteImport.update({
    id: '/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/patient/auth': typeof PatientAuthRoute
  '/queue/$doctorId': typeof QueueDoctorIdRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/onboarding': typeof AuthenticatedDoctorOnboardingRoute
  '/doctor/pending': typeof AuthenticatedDoctorPendingRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/patient/auth': typeof PatientAuthRoute
  '/queue/$doctorId': typeof QueueDoctorIdRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/onboarding': typeof AuthenticatedDoctorOnboardingRoute
  '/doctor/pending': typeof AuthenticatedDoctorPendingRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/patient/auth': typeof PatientAuthRoute
  '/queue/$doctorId': typeof QueueDoctorIdRoute
  '/_authenticated/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/_authenticated/doctor/onboarding': typeof AuthenticatedDoctorOnboardingRoute
  '/_authenticated/doctor/pending': typeof AuthenticatedDoctorPendingRoute
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/doctors'
    | '/admin'
    | '/book/$doctorId'
    | '/confirmation/$id'
    | '/doctors/$id'
    | '/patient/auth'
    | '/queue/$doctorId'
    | '/doctor/dashboard'
    | '/doctor/onboarding'
    | '/doctor/pending'
    | '/doctor/profile'
    | '/patient/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/doctors'
    | '/admin'
    | '/book/$doctorId'
    | '/confirmation/$id'
    | '/doctors/$id'
    | '/patient/auth'
    | '/queue/$doctorId'
    | '/doctor/dashboard'
    | '/doctor/onboarding'
    | '/doctor/pending'
    | '/doctor/profile'
    | '/patient/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/doctors'
    | '/_authenticated/admin'
    | '/book/$doctorId'
    | '/confirmation/$id'
    | '/doctors/$id'
    | '/patient/auth'
    | '/queue/$doctorId'
    | '/_authenticated/doctor/dashboard'
    | '/_authenticated/doctor/onboarding'
    | '/_authenticated/doctor/pending'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/patient/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoctorsRoute: typeof DoctorsRouteWithChildren
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  ConfirmationIdRoute: typeof ConfirmationIdRoute
  PatientAuthRoute: typeof PatientAuthRoute
  QueueDoctorIdRoute: typeof QueueDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$doctorId': {
      id: '/queue/$doctorId'
      path: '/queue/$doctorId'
      fullPath: '/queue/$doctorId'
      preLoaderRoute: typeof QueueDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/auth': {
      id: '/patient/auth'
      path: '/patient/auth'
      fullPath: '/patient/auth'
      preLoaderRoute: typeof PatientAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/confirmation/$id': {
      id: '/confirmation/$id'
      path: '/confirmation/$id'
      fullPath: '/confirmation/$id'
      preLoaderRoute: typeof ConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$doctorId': {
      id: '/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/dashboard': {
      id: '/_authenticated/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof AuthenticatedPatientDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/pending': {
      id: '/_authenticated/doctor/pending'
      path: '/doctor/pending'
      fullPath: '/doctor/pending'
      preLoaderRoute: typeof AuthenticatedDoctorPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/onboarding': {
      id: '/_authenticated/doctor/onboarding'
      path: '/doctor/onboarding'
      fullPath: '/doctor/onboarding'
      preLoaderRoute: typeof AuthenticatedDoctorOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/dashboard': {
      id: '/_authenticated/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AuthenticatedDoctorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDoctorDashboardRoute: typeof AuthenticatedDoctorDashboardRoute
  AuthenticatedDoctorOnboardingRoute: typeof AuthenticatedDoctorOnboardingRoute
  AuthenticatedDoctorPendingRoute: typeof AuthenticatedDoctorPendingRoute
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedPatientDashboardRoute: typeof AuthenticatedPatientDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDoctorDashboardRoute: AuthenticatedDoctorDashboardRoute,
  AuthenticatedDoctorOnboardingRoute: AuthenticatedDoctorOnboardingRoute,
  AuthenticatedDoctorPendingRoute: AuthenticatedDoctorPendingRoute,
  AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
  AuthenticatedPatientDashboardRoute: AuthenticatedPatientDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DoctorsRouteChildren {
  DoctorsIdRoute: typeof DoctorsIdRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsIdRoute: DoctorsIdRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DoctorsRoute: DoctorsRouteWithChildren,
  BookDoctorIdRoute: BookDoctorIdRoute,
  ConfirmationIdRoute: ConfirmationIdRoute,
  PatientAuthRoute: PatientAuthRoute,
  QueueDoctorIdRoute: QueueDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
